name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          # CPython versions
          - { version: "3.10", impl: "cpython" }
          - { version: "3.11", impl: "cpython" }
          # PyPy versions
          - { version: "pypy-3.10", impl: "pypy" }

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python.version }} (${{ matrix.python.impl }})
      uses: actions/setup-python@v5
      with:
        python-version: "${{ matrix.python.version }}"
        allow-prereleases: true
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip hatch
        
    - name: Build package
      run: |
        hatch build
        
    - name: Install package and dev dependencies
      run: |
        pip install -e ".[dev]"
              
    - name: Type check
      if: matrix.python.impl == 'cpython'  # Only run type checks on CPython
      run: |
        pyright  # Strict type checking
        
    - name: Lint and format
      if: matrix.python.impl == 'cpython'  # Only run linting on CPython
      run: |
        ruff check . --fix --unsafe-fixes
        ruff format --check .